
export const SAVE_WALLET_DATA = "SAVE_WALLET_DATA"
export const RESET_WALLET_DATA = "RESET_WALLET_DATA"
export const SET_Selected_DATA = "SET_Selected_DATA"
export const SAVE_BALANCE_DATA = "SAVE_BALANCE_DATA"
export const SAVE_WEB3_DATA = "SAVE_WEB3_DATA";
export const LOADING_BALANCE_PENDING = "LOADING_BALANCE_PENDING";
export const UPDATE_STACK_BALANCE = "UPDATE_STACK_BALANCE";
